### ISSUE TITLE
Failure on "Metadata" step with Agilent .d files

### ISSUE THREAD

**Issue by EmersonHernly** [VIU-Metabolomics/imzML_Writer#1]
I tried to process an imaging experiment that used an Agilent QTOF instrument and I got imzML_Writer to complete the first two steps shown ("RAW --> mzML" and "Write imzML"). However, no imzML was written and the loading bar for the "Metadata" step just had a small bar going back and forth and never began. I used default parameters if that matters.  I included the error traceback below:

```
(imzmlwriter) C:\Users\elher\OneDrive\Documents\imzML_Writer>python imzML_Writer.py
Exception in thread Thread-3 (<lambda>):
Traceback (most recent call last):
  File "C:\Users\elher\miniforge3\envs\imzmlwriter\Lib\threading.py", line 1041, in _bootstrap_inner
    self.run()
    ~~~~~~~~^^
  File "C:\Users\elher\miniforge3\envs\imzmlwriter\Lib\threading.py", line 992, in run
    self._target(*self._args, **self._kwargs)
    ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\elher\OneDrive\Documents\imzML_Writer\imzML_Writer.py", line 227, in <lambda>
    thread = threading.Thread(target=lambda:imzML_metadata_process(path_to_models,slashes,x_speed=int(speed_entry.get()),y_step=int(Y_step_entry.get()),tgt_progress=Annotate_progress,path=CD_entry.get()))
                                            ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\elher\OneDrive\Documents\imzML_Writer\gui_functions.py", line 298, in imzML_metadata_process
    annotate_imzML(target_file,model_files+sl+model_file_list[0],final_time_point,filt,x_speed=x_speed,y_step=y_step)
    ~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\elher\OneDrive\Documents\imzML_Writer\gui_functions.py", line 338, in annotate_imzML
    data = BeautifulSoup(data,'xml')
  File "C:\Users\elher\miniforge3\envs\imzmlwriter\Lib\site-packages\bs4\__init__.py", line 250, in __init__
    raise FeatureNotFound(
    ...<2 lines>...
        % ",".join(features))
bs4.FeatureNotFound: Couldn't find a tree builder with the features you requested: xml. Do you need to install a parser library?
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Users\elher\miniforge3\envs\imzmlwriter\Lib\tkinter\__init__.py", line 2068, in __call__
    return self.func(*args)
           ~~~~~~~~~^^^^^^^
  File "C:\Users\elher\miniforge3\envs\imzmlwriter\Lib\tkinter\__init__.py", line 862, in callit
    func(*args)
    ~~~~^^^^^^^
  File "C:\Users\elher\OneDrive\Documents\imzML_Writer\imzML_Writer.py", line 259, in check_metadata_completion
    populate_list(CD_entry.get())
    ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^
  File "C:\Users\elher\OneDrive\Documents\imzML_Writer\imzML_Writer.py", line 52, in populate_list
    files = os.listdir(dir)
FileNotFoundError: [WinError 3] The system cannot find the path specified: 'C:/Users/elher/Desktop/raw_files/Soybean93Y21-S10-sample2-00'
```

**Comment by JosephMonaghan** [comment]
Hi Emerson,

Thanks for posting, and sorry you're encountering an error! Our Agilent test data set wasn't the deepest (few GC-MS runs for pseudo-images), so I'm not surprised errors are cropping up with real data. From the call stack and the lack of imzML file, I think it's probably struggling to find the scan filters to separate the file(s) if appropriate. Would you be willing to (privately) share some raw data that I can tinker with?

Also - Is the QToF writing data with ion mobility as well? If so the extra dimension of drift time may be the issue.

Thanks,

Joseph

**Comment by EmersonHernly** [comment]
Hi Joseph,

Sorry I missed your reply! The files do not have ion mobility information, but we do have images that use ion mobility so it would be nice if imzML_Writer would be able to properly use that data. Here is a link to a few line scans that you can use for testing, you will just need to request access: 
https://purdue0-my.sharepoint.com/:f:/r/personal/ehernly_purdue_edu/Documents/Example%20QTOF%20line%20scans?csf=1&web=1&e=iRZoDv

Best,
Emerson

**Comment by JosephMonaghan** [comment]
Hey Emerson,

It doesn't seem to be giving me an option to request access - looks like maybe the link is configured for only your institution? If you're able to manually add permissions for me (Joseph.Monaghan@viu.ca) I can retrieve the files from there. If not, [here's ](https://viucanada-my.sharepoint.com/:f:/g/personal/joseph_monaghan_viu_ca/EihjXvTJ1WpNsh6R-y4kySMByFpcr3YLoa--7JSbmt9PlQ?email=ehernly%40purdue.edu&e=1czhZC) a OneDrive folder that we can try the reverse with.

RE: Ion mobility data - this is definitely something we'd be keen to add. We don't have an instrument with ion mobility right now, so if you're willing to share some line scans for that I can start tinkering there as well.

Happy new year!

Joseph

**Comment by EmersonHernly** [comment]
Hi Joseph,

I uploaded a few example files for Agilent QToF with and without mobility and a few from a timsTOF with ion mobility to your OneDrive link. 

Happy new Year to you as well!
Emerson

**Comment by JosephMonaghan** [comment]
Hey Emerson,

Thanks for uploading the files - I've started trying to parse through them now but I think things might've gotten mixed up during your upload so want to make sure I understand what's in each of the folders:

**1. Example QTOF lines with ion mobility** - Agilent data with ion mobility on. I can actually generate an imzML for this one, but it isn't doing anything for the ion mobility (yet!) so the resulting image doesn't make much sense.

**2. Example QTOF line scans no ion mobility** - Should be agilent data with no ion mobility? The produced mzML tells me this is Bruker data and has similar file structure to folder 3 so wondering if this got the wrong files by mistake

**3. Example TIMS-TOF lines with ion mobility** - Bruker data with tims mode on, haven't had a chance to try anything with this one yet

Can you confirm this is what I'm looking at, and if I'm right about folder 2, provide some Agilent data with no ion mobility as well?

Thanks,

Joseph


PS - Quick note if you're trying anything on your end, these files end up quite a bit bigger than the .raw files I built everything with, so the GUI elements/waiting loops for mzML conversion may break and leave you with an incomplete mzML for the final line scan file. Passing that one through msconvert manually should work as a duct-tape fix while I work on getting a cleaner solution working.

**Comment by EmersonHernly** [comment]
Hi Joseph,

Congratulations on the publication in Analytical Chemistry!
Sorry about the slow responses, I am not getting any notifications even though I turned them on.

The actual data in the files might be somewhat meaningless, as it is just the first few lines of the image, where only a small portion of the spectra are from the sample, with the rest being the glass slide used to mount the tissue. You are definitely correct about the data in the second folder being Bruker data. Sorry about that mistake. I uploaded some Agilent data with no mobility data.

**Comment by JosephMonaghan** [comment]
Hey @EmersonHernly 

Thanks! And thank you for the updated files. No worries on slow responses, not the fastest time of year for any of us in academia.

I just pushed a new version of the package (v1.1.0) to pypi that is working on my end to convert the latest files you sent. If/when you get a chance, can you try re-installing and let me know if this resolved the issue?

Note that there is likely still an issue with parsing scan filters. For whatever reason, msconvert doesn't seem to write these for Agilent files. I've got some ideas to generate our own from the data but hoping to make sure we've got the basics working first.

-Joseph
